[project]
name = "pyfmreader"
version = "0.1.3"

[build-system]
requires = ["setuptools>=61.0", "numpy", "pandas", "tifffile"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]